import { SignaturePattern } from './types';

export const COMPREHENSIVE_SIGNATURES: SignaturePattern[] = [
  // ==========================================
  // 1. RASTER & VECTOR IMAGES
  // ==========================================
  {
    id: 'png',
    name: 'Portable Network Graphics',
    extension: 'PNG',
    category: 'Images',
    mimeType: 'image/png',
    magicBytesHex: '89 50 4E 47 0D 0A 1A 0A',
    offset: 0,
    confidence: 'High',
    description: 'Lossless raster image format with 8-bit to 48-bit color depth and full alpha channel transparency.',
    meaning: '8-byte PNG header: \\x89 detects 8-bit clean transfer, "PNG" ASCII identifier, DOS CRLF line-end check (0D 0A), DOS EOF (1A), and Unix LF (0A).',
    asciiRepresentation: '.PNG....',
  },
  {
    id: 'jpg',
    name: 'JPEG / JFIF Photographic Image',
    extension: 'JPG',
    category: 'Images',
    mimeType: 'image/jpeg',
    magicBytesHex: 'FF D8 FF',
    offset: 0,
    confidence: 'High',
    description: 'Universal standard lossy photographic compression format standardized by ISO/IEC 10918-1.',
    meaning: 'Start of Image (SOI) marker (FF D8) followed by application marker (FF E0 for JFIF, FF E1 for Exif, or FF DB/EE/E2).',
    asciiRepresentation: '....',
  },
  {
    id: 'gif',
    name: 'Graphics Interchange Format',
    extension: 'GIF',
    category: 'Images',
    mimeType: 'image/gif',
    magicBytesHex: '47 49 46 38',
    offset: 0,
    confidence: 'High',
    description: 'CompuServe 8-bit palletized raster graphic format supporting frame delay animation and binary transparency.',
    meaning: 'ASCII signature "GIF8" (either GIF87a or GIF89a version stamp) followed by logical screen width and height descriptors.',
    asciiRepresentation: 'GIF8',
  },
  {
    id: 'webp',
    name: 'Google WebP Image Format',
    extension: 'WEBP',
    category: 'Images',
    mimeType: 'image/webp',
    magicBytesHex: '52 49 46 46',
    offset: 0,
    confidence: 'High',
    description: 'Google media format providing 25-35% higher compression than JPEG/PNG, with lossy, lossless, and animated WebP VP8/VP8X streams.',
    meaning: 'RIFF master container header (52 49 46 46) followed by 4-byte chunk length and 4-byte "WEBP" FOURCC form type (57 45 42 50).',
    asciiRepresentation: 'RIFF....WEBP',
    secondaryCheck: (bytes) => {
      if (bytes.length < 12) return false;
      // Check bytes 8..11 for 'WEBP'
      return bytes[8] === 0x57 && bytes[9] === 0x45 && bytes[10] === 0x42 && bytes[11] === 0x50;
    },
  },
  {
    id: 'heic',
    name: 'High Efficiency Image Container',
    extension: 'HEIC',
    category: 'Images',
    mimeType: 'image/heic',
    magicBytesHex: '66 74 79 70 68 65 69 63',
    offset: 4,
    confidence: 'High',
    description: 'ISO/IEC 23008-12 image container utilizing HEVC intra-frame compression, standard on modern Apple iOS cameras.',
    meaning: 'ISO Base Media File Format (ISOBMFF) "ftyp" box at offset 4 with major brand "heic" or compatible brand "mif1/heic".',
    asciiRepresentation: 'ftypheic',
    secondaryCheck: (bytes, ascii) => {
      const sub = ascii.slice(4, 24).toLowerCase();
      return sub.includes('heic') || sub.includes('heix') || sub.includes('hevc') || sub.includes('mif1');
    },
  },
  {
    id: 'avif',
    name: 'AV1 Image File Format',
    extension: 'AVIF',
    category: 'Images',
    mimeType: 'image/avif',
    magicBytesHex: '66 74 79 70 61 76 69 66',
    offset: 4,
    confidence: 'High',
    description: 'Next-generation open image coding format by Alliance for Open Media (AOMedia) compressing AV1 video keyframes.',
    meaning: 'ISOBMFF "ftyp" box with major brand "avif" or "avis" and compatibility brands.',
    asciiRepresentation: 'ftypavif',
    secondaryCheck: (bytes, ascii) => {
      const sub = ascii.slice(4, 24).toLowerCase();
      return sub.includes('avif') || sub.includes('avis');
    },
  },
  {
    id: 'tiff',
    name: 'Tagged Image File Format',
    extension: 'TIFF',
    category: 'Images',
    mimeType: 'image/tiff',
    magicBytesHex: '49 49 2A 00',
    offset: 0,
    confidence: 'High',
    description: 'High-color uncompressed or lossless LZW/ZIP raster graphics format designed for desktop publishing and scanning.',
    meaning: 'Byte-order indicator: "II*\\0" (49 49 2A 00 for Little-Endian Intel) or "MM\\0*" (4D 4D 00 2A for Big-Endian Motorola) with 42 version stamp.',
    asciiRepresentation: 'II*.',
    secondaryCheck: (bytes) => {
      if (bytes.length < 4) return false;
      const isIntel = bytes[0] === 0x49 && bytes[1] === 0x49 && bytes[2] === 0x2A && bytes[3] === 0x00;
      const isMotorola = bytes[0] === 0x4D && bytes[1] === 0x4D && bytes[2] === 0x00 && bytes[3] === 0x2A;
      return isIntel || isMotorola;
    },
  },
  {
    id: 'bmp',
    name: 'Windows Bitmap Graphic',
    extension: 'BMP',
    category: 'Images',
    mimeType: 'image/bmp',
    magicBytesHex: '42 4D',
    offset: 0,
    confidence: 'High',
    description: 'Microsoft device-independent bitmap storing uncompressed pixel color arrays with optional RLE compression.',
    meaning: '2-byte ASCII signature "BM" (42 4D) identifying Windows DIB bitmap header structure followed by 4-byte file size.',
    asciiRepresentation: 'BM',
  },
  {
    id: 'ico',
    name: 'Windows Icon File',
    extension: 'ICO',
    category: 'Images',
    mimeType: 'image/x-icon',
    magicBytesHex: '00 00 01 00',
    offset: 0,
    confidence: 'High',
    description: 'Windows multi-resolution icon container holding one or more small BMP or PNG image entries.',
    meaning: 'ICONDIR header: 2 bytes reserved (00 00), 2 bytes resource type (01 00 for icon, 02 00 for cursor), followed by 2-byte image count.',
    asciiRepresentation: '....',
  },
  {
    id: 'psd',
    name: 'Adobe Photoshop Master Document',
    extension: 'PSD',
    category: 'Images',
    mimeType: 'image/vnd.adobe.photoshop',
    magicBytesHex: '38 42 50 53',
    offset: 0,
    confidence: 'High',
    description: 'Adobe Photoshop native document containing layers, adjustment masks, vector shapes, color channels, and blending modes.',
    meaning: '4-byte ASCII signature "8BPS" (38 42 50 53) followed by 2-byte version number (00 01 for PSD, 00 02 for PSB Large Document).',
    asciiRepresentation: '8BPS',
  },
  {
    id: 'svg',
    name: 'Scalable Vector Graphics',
    extension: 'SVG',
    category: 'Images',
    mimeType: 'image/svg+xml',
    magicBytesHex: '3C 73 76 67',
    offset: 0,
    confidence: 'High',
    description: 'W3C open standard XML vector image defining scalable geometric paths, gradients, text, and SVG animations.',
    meaning: 'XML markup starting with "<svg" tag or "<?xml" declaration containing SVG namespace attribute.',
    asciiRepresentation: '<svg',
    secondaryCheck: (bytes, ascii) => {
      const lower = ascii.slice(0, 100).toLowerCase();
      return lower.includes('<svg') || (lower.includes('<?xml') && lower.includes('svg'));
    },
  },

  // ==========================================
  // 2. DOCUMENTS & E-BOOKS
  // ==========================================
  {
    id: 'pdf',
    name: 'Portable Document Format',
    extension: 'PDF',
    category: 'Documents',
    mimeType: 'application/pdf',
    magicBytesHex: '25 50 44 46',
    offset: 0,
    confidence: 'High',
    description: 'Adobe ISO 32000 fixed-layout document standard encoding text, fonts, vector illustrations, and interactive forms.',
    meaning: 'ASCII signature "%PDF-" followed by specification version number (e.g. %PDF-1.4, %PDF-1.7, %PDF-2.0).',
    asciiRepresentation: '%PDF',
  },
  {
    id: 'docx',
    name: 'Microsoft Word OpenXML Document',
    extension: 'DOCX',
    category: 'Documents',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    magicBytesHex: '50 4B 03 04',
    offset: 0,
    confidence: 'High',
    description: 'Microsoft Office Open XML word processing document packaged as a compressed ZIP container holding XML streams.',
    meaning: 'PKZIP header with internal directory containing "[Content_Types].xml" and "word/document.xml".',
    asciiRepresentation: 'PK..',
    isContainer: true,
    secondaryCheck: (bytes, ascii, ext) => {
      if (ext === 'docx') return true;
      return ascii.includes('word/') || ascii.includes('word/document.xml');
    },
  },
  {
    id: 'xlsx',
    name: 'Microsoft Excel OpenXML Spreadsheet',
    extension: 'XLSX',
    category: 'Documents',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    magicBytesHex: '50 4B 03 04',
    offset: 0,
    confidence: 'High',
    description: 'Microsoft Excel XML-based spreadsheet container containing workbook sheets, formulas, styles, and calculation tables.',
    meaning: 'PKZIP container containing "[Content_Types].xml" and "xl/workbook.xml" or "xl/worksheets/".',
    asciiRepresentation: 'PK..',
    isContainer: true,
    secondaryCheck: (bytes, ascii, ext) => {
      if (ext === 'xlsx') return true;
      return ascii.includes('xl/') || ascii.includes('xl/workbook.xml');
    },
  },
  {
    id: 'pptx',
    name: 'Microsoft PowerPoint Presentation',
    extension: 'PPTX',
    category: 'Documents',
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    magicBytesHex: '50 4B 03 04',
    offset: 0,
    confidence: 'High',
    description: 'Microsoft PowerPoint Open XML slide deck container with slide masters, transition effects, and embedded assets.',
    meaning: 'PKZIP container containing "[Content_Types].xml" and "ppt/presentation.xml" or "ppt/slides/".',
    asciiRepresentation: 'PK..',
    isContainer: true,
    secondaryCheck: (bytes, ascii, ext) => {
      if (ext === 'pptx') return true;
      return ascii.includes('ppt/') || ascii.includes('ppt/presentation.xml');
    },
  },
  {
    id: 'doc',
    name: 'Microsoft Word 97-2003 Binary Document',
    extension: 'DOC',
    category: 'Documents',
    mimeType: 'application/msword',
    magicBytesHex: 'D0 CF 11 E0 A1 B1 1A E1',
    offset: 0,
    confidence: 'High',
    description: 'Legacy Microsoft Compound File Binary Format (CFBF / OLE Structured Storage) for Word documents.',
    meaning: 'Microsoft OLE Compound Document Header (D0 CF 11 E0 A1 B1 1A E1) storing binary WordDocument streams.',
    asciiRepresentation: '........',
    secondaryCheck: (bytes, ascii, ext) => {
      return ext === 'doc' || ascii.includes('WordDocument') || ascii.includes('Microsoft Word');
    },
  },
  {
    id: 'xls',
    name: 'Microsoft Excel 97-2003 Binary Spreadsheet',
    extension: 'XLS',
    category: 'Documents',
    mimeType: 'application/vnd.ms-excel',
    magicBytesHex: 'D0 CF 11 E0 A1 B1 1A E1',
    offset: 0,
    confidence: 'High',
    description: 'Legacy Microsoft Compound File Binary Format for Excel BIFF8 binary workbooks.',
    meaning: 'OLE Compound Storage header storing Workbook/Book binary spreadsheet data.',
    asciiRepresentation: '........',
    secondaryCheck: (bytes, ascii, ext) => {
      return ext === 'xls' || ascii.includes('Workbook') || ascii.includes('Book');
    },
  },
  {
    id: 'epub',
    name: 'Electronic Publication E-Book',
    extension: 'EPUB',
    category: 'Documents',
    mimeType: 'application/epub+zip',
    magicBytesHex: '50 4B 03 04',
    offset: 0,
    confidence: 'High',
    description: 'International Digital Publishing Forum (IDPF) standard reflowable e-book packaging XHTML, CSS, and metadata.',
    meaning: 'PKZIP container starting with uncompressed "mimetype" file containing ASCII string "application/epub+zip".',
    asciiRepresentation: 'PK..mimetypeapplication/epub+zip',
    secondaryCheck: (bytes, ascii) => {
      return ascii.includes('mimetypeapplication/epub+zip') || ascii.includes('META-INF/container.xml');
    },
  },
  {
    id: 'rtf',
    name: 'Rich Text Format',
    extension: 'RTF',
    category: 'Documents',
    mimeType: 'application/rtf',
    magicBytesHex: '7B 5C 72 74 66',
    offset: 0,
    confidence: 'High',
    description: 'Microsoft cross-platform formatted text encoding fonts, bold/italic markup, and tables via 7-bit ASCII control words.',
    meaning: 'ASCII group opening brace and control word "{\\rtf" (7B 5C 72 74 66) followed by specification version (e.g. \\rtf1).',
    asciiRepresentation: '{\\rtf',
  },

  // ==========================================
  // 3. ARCHIVES & CONTAINERS
  // ==========================================
  {
    id: 'zip',
    name: 'ZIP Compressed Archive',
    extension: 'ZIP',
    category: 'Archives',
    mimeType: 'application/zip',
    magicBytesHex: '50 4B 03 04',
    offset: 0,
    confidence: 'High',
    description: 'Phil Katz PKZIP lossless data compression and packaging format utilizing Deflate and DEFLATE64 algorithms.',
    meaning: 'Local file header signature "PK\\x03\\x04" (50 4B 03 04), "PK\\x05\\x06" (Empty archive), or "PK\\x07\\x08" (Spanned archive).',
    asciiRepresentation: 'PK..',
    isContainer: true,
  },
  {
    id: 'rar',
    name: 'Roshal Archive Compressed File',
    extension: 'RAR',
    category: 'Archives',
    mimeType: 'application/vnd.rar',
    magicBytesHex: '52 61 72 21 1A 07',
    offset: 0,
    confidence: 'High',
    description: 'Eugene Roshal proprietary high-ratio data compression archive supporting solid blocks, recovery volumes, and AES-256.',
    meaning: 'ASCII "Rar!\\x1A\\x07" for RAR 4.x (52 61 72 21 1A 07 00) or RAR 5.x (52 61 72 21 1A 07 01 00).',
    asciiRepresentation: 'Rar!..',
  },
  {
    id: '7z',
    name: '7-Zip Compressed Archive',
    extension: '7Z',
    category: 'Archives',
    mimeType: 'application/x-7z-compressed',
    magicBytesHex: '37 7A BC AF 27 1C',
    offset: 0,
    confidence: 'High',
    description: 'Igor Pavlov open architecture high-compression container using LZMA and LZMA2 algorithms with AES-256 header encryption.',
    meaning: '6-byte signature "7z\\xBC\\xAF\'\\x1C" (37 7A BC AF 27 1C) followed by 2-byte archive version number.',
    asciiRepresentation: '7z..\'',
  },
  {
    id: 'tar',
    name: 'Tape Archive Container',
    extension: 'TAR',
    category: 'Archives',
    mimeType: 'application/x-tar',
    magicBytesHex: '75 73 74 61 72',
    offset: 257,
    confidence: 'High',
    description: 'Standard Unix POSIX tarball packaging multiple files, directory trees, file permissions, and symbolic links.',
    meaning: 'POSIX "ustar" (75 73 74 61 72) magic string located at byte offset 257 in the 512-byte header block.',
    asciiRepresentation: 'ustar',
  },
  {
    id: 'gz',
    name: 'Gzip Compressed Stream',
    extension: 'GZ',
    category: 'Archives',
    mimeType: 'application/gzip',
    magicBytesHex: '1F 8B',
    offset: 0,
    confidence: 'High',
    description: 'GNU zip single-file compression format utilizing the Deflate algorithm standardized in RFC 1952.',
    meaning: 'Gzip ID bytes (1F 8B) followed by compression method (08 for Deflate) and flag bytes for original filename/timestamp.',
    asciiRepresentation: '..',
  },
  {
    id: 'bz2',
    name: 'Bzip2 Compressed File',
    extension: 'BZ2',
    category: 'Archives',
    mimeType: 'application/x-bzip2',
    magicBytesHex: '42 5A 68',
    offset: 0,
    confidence: 'High',
    description: 'Julian Seward high-efficiency block-sorting compression format using the Burrows-Wheeler transform and Huffman coding.',
    meaning: 'ASCII "BZh" (42 5A 68) followed by block size number (e.g. 1 to 9 representing 100k-900k memory blocks).',
    asciiRepresentation: 'BZh',
  },
  {
    id: 'xz',
    name: 'XZ Lossless Data Container',
    extension: 'XZ',
    category: 'Archives',
    mimeType: 'application/x-xz',
    magicBytesHex: 'FD 37 7A 58 5A 00',
    offset: 0,
    confidence: 'High',
    description: 'Modern general-purpose data compression format utilizing the LZMA2 algorithm, successor to LZMA format.',
    meaning: '6-byte stream header "\\xFD7zXZ\\x00" (FD 37 7A 58 5A 00) followed by 2-byte stream flags and CRC32 verification.',
    asciiRepresentation: '.7zXZ.',
  },
  {
    id: 'iso',
    name: 'ISO 9660 Optical Disc Image',
    extension: 'ISO',
    category: 'Archives',
    mimeType: 'application/x-iso9660-image',
    magicBytesHex: '43 44 30 30 31',
    offset: 32769,
    confidence: 'High',
    description: 'Sector-by-sector binary image of an optical disc filesystem standardized by ISO 9660 / UDF.',
    meaning: 'ASCII standard identifier "CD001" (43 44 30 30 31) located at sector 16 (offset 0x8001 / 32769 bytes).',
    asciiRepresentation: 'CD001',
  },

  // ==========================================
  // 4. AUDIO & VIDEO MEDIA
  // ==========================================
  {
    id: 'mp4',
    name: 'MPEG-4 Part 14 Video Container',
    extension: 'MP4',
    category: 'Audio & Video',
    mimeType: 'video/mp4',
    magicBytesHex: '66 74 79 70',
    offset: 4,
    confidence: 'High',
    description: 'Universal digital multimedia container standard for video (H.264/H.265/AV1), audio (AAC), subtitles, and chapters.',
    meaning: 'ISOBMFF "ftyp" box at offset 4 with major brand "mp41", "mp42", "isom", or "dash".',
    asciiRepresentation: 'ftyp',
    secondaryCheck: (bytes, ascii) => {
      const sub = ascii.slice(4, 24).toLowerCase();
      return sub.includes('mp4') || sub.includes('isom') || sub.includes('avc1') || sub.includes('dash');
    },
  },
  {
    id: 'mov',
    name: 'Apple QuickTime Movie',
    extension: 'MOV',
    category: 'Audio & Video',
    mimeType: 'video/quicktime',
    magicBytesHex: '66 74 79 70 71 74 20 20',
    offset: 4,
    confidence: 'High',
    description: 'Apple QuickTime video container encoding ProRes, H.264, and multi-track audio tracks with timecodes.',
    meaning: 'ISOBMFF "ftyp" box with major brand "qt  " (66 74 79 70 71 74 20 20) or wide/moov container box.',
    asciiRepresentation: 'ftypqt  ',
    secondaryCheck: (bytes, ascii) => {
      const sub = ascii.slice(4, 24).toLowerCase();
      return sub.includes('qt  ') || sub.includes('moov');
    },
  },
  {
    id: 'mkv',
    name: 'Matroska Multimedia Container',
    extension: 'MKV',
    category: 'Audio & Video',
    mimeType: 'video/x-matroska',
    magicBytesHex: '1A 45 DF A3',
    offset: 0,
    confidence: 'High',
    description: 'Open standard extensible multimedia container holding unlimited video, audio, and ASS subtitle tracks.',
    meaning: 'Extensible Binary Meta Language (EBML) header (1A 45 DF A3) with DocType string "matroska".',
    asciiRepresentation: '.E..',
    secondaryCheck: (bytes, ascii, ext) => {
      return ext === 'mkv' || ascii.includes('matroska');
    },
  },
  {
    id: 'webm',
    name: 'WebM HTML5 Video Container',
    extension: 'WEBM',
    category: 'Audio & Video',
    mimeType: 'video/webm',
    magicBytesHex: '1A 45 DF A3',
    offset: 0,
    confidence: 'High',
    description: 'Google open-source royalty-free media container holding VP8, VP9, or AV1 video with Opus or Vorbis audio.',
    meaning: 'EBML master element with DocType string "webm".',
    asciiRepresentation: '.E..',
    secondaryCheck: (bytes, ascii, ext) => {
      return ext === 'webm' || ascii.includes('webm');
    },
  },
  {
    id: 'mp3',
    name: 'MPEG Audio Layer III',
    extension: 'MP3',
    category: 'Audio & Video',
    mimeType: 'audio/mpeg',
    magicBytesHex: '49 44 33',
    offset: 0,
    confidence: 'High',
    description: 'Fraunhofer IIS lossy digital audio compression format standard for audio music playback.',
    meaning: 'ID3v2 metadata header ("ID3" / 49 44 33) or MPEG sync frame word (FF FB / FF F3 / FF F2) at offset 0.',
    asciiRepresentation: 'ID3',
    secondaryCheck: (bytes) => {
      if (bytes.length < 3) return false;
      const isId3 = bytes[0] === 0x49 && bytes[1] === 0x44 && bytes[2] === 0x33;
      const isSync = bytes[0] === 0xFF && (bytes[1] === 0xFB || bytes[1] === 0xF3 || bytes[1] === 0xF2);
      return isId3 || isSync;
    },
  },
  {
    id: 'wav',
    name: 'Waveform Audio File Format',
    extension: 'WAV',
    category: 'Audio & Video',
    mimeType: 'audio/wav',
    magicBytesHex: '52 49 46 46',
    offset: 0,
    confidence: 'High',
    description: 'Microsoft & IBM RIFF container storing uncompressed linear pulse-code modulation (LPCM) studio audio.',
    meaning: 'RIFF chunk header (52 49 46 46) followed by 4-byte chunk size and "WAVE" format identifier (57 41 56 45).',
    asciiRepresentation: 'RIFF....WAVE',
    secondaryCheck: (bytes) => {
      if (bytes.length < 12) return false;
      return bytes[8] === 0x57 && bytes[9] === 0x41 && bytes[10] === 0x56 && bytes[11] === 0x45;
    },
  },
  {
    id: 'flac',
    name: 'Free Lossless Audio Codec',
    extension: 'FLAC',
    category: 'Audio & Video',
    mimeType: 'audio/flac',
    magicBytesHex: '66 4C 61 43',
    offset: 0,
    confidence: 'High',
    description: 'Xiph.Org open lossless audio format compressing CD and Hi-Res studio master recordings without audio degradation.',
    meaning: 'ASCII marker "fLaC" (66 4C 61 43) followed by STREAMINFO metadata block containing sample rate and channels.',
    asciiRepresentation: 'fLaC',
  },
  {
    id: 'ogg',
    name: 'Ogg Vorbis / Opus Multimedia Container',
    extension: 'OGG',
    category: 'Audio & Video',
    mimeType: 'audio/ogg',
    magicBytesHex: '4F 67 67 53',
    offset: 0,
    confidence: 'High',
    description: 'Xiph.Org Foundation open container format designed for streaming Vorbis, Opus, FLAC, and Theora media.',
    meaning: 'ASCII capture pattern "OggS" (4F 67 67 53) identifying page sync header followed by stream serial number.',
    asciiRepresentation: 'OggS',
  },

  // ==========================================
  // 5. CAD, 3D & ENGINEERING
  // ==========================================
  {
    id: 'dwg',
    name: 'AutoCAD Computer-Aided Design Drawing',
    extension: 'DWG',
    category: 'CAD & 3D',
    mimeType: 'image/vnd.dwg',
    magicBytesHex: '41 43 31 30',
    offset: 0,
    confidence: 'High',
    description: 'Autodesk native 2D/3D vector design drawing binary database format standard across architectural & engineering CAD.',
    meaning: 'ASCII version header "AC10" (41 43 31 30) followed by 2-byte release code (e.g. AC1032 for AutoCAD 2018-2024, AC1027 for 2013).',
    asciiRepresentation: 'AC10',
  },
  {
    id: 'dxf',
    name: 'Drawing Exchange Format',
    extension: 'DXF',
    category: 'CAD & 3D',
    mimeType: 'application/dxf',
    magicBytesHex: '30 0A 53 45 43 54 49 4F 4E',
    offset: 0,
    confidence: 'High',
    description: 'Autodesk open ASCII/binary data interoperability format enabling cross-application CAD geometry exchange.',
    meaning: 'DXF group code 0 and string "SECTION" marking the header block in ASCII CAD exchange files.',
    asciiRepresentation: '0.SECTION',
    secondaryCheck: (bytes, ascii) => {
      return ascii.slice(0, 40).includes('SECTION') && ascii.slice(0, 40).includes('HEADER');
    },
  },
  {
    id: 'stl',
    name: 'Stereolithography 3D Mesh',
    extension: 'STL',
    category: 'CAD & 3D',
    mimeType: 'model/stl',
    magicBytesHex: '73 6F 6C 69 64',
    offset: 0,
    confidence: 'Medium',
    description: '3D Systems polygon triangle mesh format standard for 3D printing, rapid prototyping, and additive manufacturing.',
    meaning: 'ASCII keyword "solid" at offset 0, or 80-byte binary header followed by 4-byte little-endian triangle facet count.',
    asciiRepresentation: 'solid',
    secondaryCheck: (bytes, ascii, ext) => {
      if (ext === 'stl') return true;
      return ascii.startsWith('solid');
    },
  },
  {
    id: 'step',
    name: 'Standard for the Exchange of Product Model Data',
    extension: 'STEP',
    category: 'CAD & 3D',
    mimeType: 'model/step',
    magicBytesHex: '49 53 4F 2D 31 30 33 30 33 2D 32 31',
    offset: 0,
    confidence: 'High',
    description: 'ISO 10303-21 open international exchange standard representing 3D mechanical assemblies and solid B-Rep geometry.',
    meaning: 'ASCII standard header "ISO-10303-21;" identifying STEP Part 21 clear text encoding.',
    asciiRepresentation: 'ISO-10303-21',
  },

  // ==========================================
  // 6. SYSTEM & EXECUTABLES
  // ==========================================
  {
    id: 'exe',
    name: 'Windows Portable Executable',
    extension: 'EXE',
    category: 'System & Executables',
    mimeType: 'application/x-msdownload',
    magicBytesHex: '4D 5A',
    offset: 0,
    confidence: 'High',
    description: 'Microsoft Windows 32-bit/64-bit native executable binary file format (PE/COFF) containing compiled machine code.',
    meaning: 'Mark Zbikowski DOS stub header signature "MZ" (4D 5A) followed by PE pointer at offset 0x3C leading to "PE\\0\\0" (50 45 00 00).',
    asciiRepresentation: 'MZ',
    isExecutable: true,
  },
  {
    id: 'elf',
    name: 'Linux Executable and Linkable Format',
    extension: 'ELF',
    category: 'System & Executables',
    mimeType: 'application/x-executable',
    magicBytesHex: '7F 45 4C 46',
    offset: 0,
    confidence: 'High',
    description: 'Standard Linux and Unix binary format for compiled executables, shared libraries (.so), and core dumps.',
    meaning: '4-byte ELF identification sequence (7F 45 4C 46) followed by class byte (01 for 32-bit, 02 for 64-bit) and endianness indicator.',
    asciiRepresentation: '.ELF',
    isExecutable: true,
  },
  {
    id: 'apk',
    name: 'Android Application Package',
    extension: 'APK',
    category: 'System & Executables',
    mimeType: 'application/vnd.android.package-archive',
    magicBytesHex: '50 4B 03 04',
    offset: 0,
    confidence: 'High',
    description: 'Google Android application package container holding compiled Dalvik/ART bytecode (classes.dex) and assets.',
    meaning: 'PKZIP container holding "AndroidManifest.xml", "classes.dex", and "resources.arsc".',
    asciiRepresentation: 'PK..',
    isContainer: true,
    secondaryCheck: (bytes, ascii, ext) => {
      if (ext === 'apk') return true;
      return ascii.includes('AndroidManifest.xml') || ascii.includes('classes.dex');
    },
  },

  // ==========================================
  // 7. DATABASES & CODE
  // ==========================================
  {
    id: 'sqlite',
    name: 'SQLite 3 Database File',
    extension: 'SQLITE',
    category: 'Databases',
    mimeType: 'application/x-sqlite3',
    magicBytesHex: '53 51 4C 69 74 65 20 66 6F 72 6D 61 74 20 33 00',
    offset: 0,
    confidence: 'High',
    description: 'Self-contained, serverless, zero-configuration SQL database engine file format storing structured B-tree tables.',
    meaning: '16-byte null-terminated ASCII header string "SQLite format 3\\0" (53 51 4C 69 74 65 20 66 6F 72 6D 61 74 20 33 00).',
    asciiRepresentation: 'SQLite format 3.',
  },
];
